### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by TheDanniCraft** [unmade/shelf-showcase#9]
When I run `docker compose up` I get this error:
```
shelf-showcase-redis-1         | 1:C 24 Nov 2022 20:49:09.435 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
shelf-showcase-redis-1         | 1:C 24 Nov 2022 20:49:09.435 # Redis version=7.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
shelf-showcase-redis-1         | 1:C 24 Nov 2022 20:49:09.435 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
shelf-showcase-redis-1         | 1:M 24 Nov 2022 20:49:09.436 * monotonic clock: POSIX clock_gettime
shelf-showcase-redis-1         | 1:M 24 Nov 2022 20:49:09.439 * Running mode=standalone, port=6379.
shelf-showcase-redis-1         | 1:M 24 Nov 2022 20:49:09.439 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
shelf-showcase-redis-1         | 1:M 24 Nov 2022 20:49:09.439 # Server initialized
shelf-showcase-redis-1         | 1:M 24 Nov 2022 20:49:09.444 * Ready to accept connections
shelf-showcase-edgedb-1        | ERROR: the file specified by EDGEDB_SERVER_TLS_KEY_FILE (/certs/edbprivkey.dev.pem) does not exist.
shelf-showcase-edgedb-1 exited with code 1
shelf-showcase-shelf-back-1    | Traceback (most recent call last):
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/src/shelf-back/manage.py", line 95, in <module>
shelf-showcase-shelf-back-1    |     cli()
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/src/shelf-back/manage.py", line 91, in migrate
shelf-showcase-shelf-back-1    |     asyncio.run(run_migration(schema_declaration))
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
shelf-showcase-shelf-back-1    |     return runner.run(main)
shelf-showcase-shelf-back-1    |            ^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
shelf-showcase-shelf-back-1    |     return self._loop.run_until_complete(task)
shelf-showcase-shelf-back-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/src/shelf-back/manage.py", line 85, in run_migration
shelf-showcase-shelf-back-1    |     async with db.create_client() as conn:
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
shelf-showcase-shelf-back-1    |     return await anext(self.gen)
shelf-showcase-shelf-back-1    |            ^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/src/shelf-back/app/db.py", line 68, in create_client
shelf-showcase-shelf-back-1    |     async with edgedb.create_async_client(
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/asyncio_client.py", line 356, in __aenter__
shelf-showcase-shelf-back-1    |     return await self.ensure_connected()
shelf-showcase-shelf-back-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/asyncio_client.py", line 336, in ensure_connected
shelf-showcase-shelf-back-1    |     await self._impl.ensure_connected()
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/base_client.py", line 654, in ensure_connected
shelf-showcase-shelf-back-1    |     await ch.connect()
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/base_client.py", line 361, in connect
shelf-showcase-shelf-back-1    |     self._con = await self._pool._get_new_connection()
shelf-showcase-shelf-back-1    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/base_client.py", line 594, in _get_new_connection
shelf-showcase-shelf-back-1    |     con = await self._maybe_get_first_connection()
shelf-showcase-shelf-back-1    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/asyncio_client.py", line 183, in _maybe_get_first_connection
shelf-showcase-shelf-back-1    |     return await self._get_first_connection()
shelf-showcase-shelf-back-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/base_client.py", line 569, in _get_first_connection
shelf-showcase-shelf-back-1    |     connect_config, client_config = con_utils.parse_connect_arguments(
shelf-showcase-shelf-back-1    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 964, in parse_connect_arguments
shelf-showcase-shelf-back-1    |     connect_config = _parse_connect_dsn_and_args(
shelf-showcase-shelf-back-1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 509, in _parse_connect_dsn_and_args
shelf-showcase-shelf-back-1    |     has_compound_options = _resolve_config_options(
shelf-showcase-shelf-back-1    |                            ^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 826, in _resolve_config_options
shelf-showcase-shelf-back-1    |     resolved_config.set_tls_ca_file(*tls_ca_file)
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 222, in set_tls_ca_file
shelf-showcase-shelf-back-1    |     self._set_param('tls_ca_data', ca_file, source, read_ca_file)
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 196, in _set_param
shelf-showcase-shelf-back-1    |     validator(value) if validator else value
shelf-showcase-shelf-back-1    |     ^^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 219, in read_ca_file
shelf-showcase-shelf-back-1    |     with open(file_path) as f:
shelf-showcase-shelf-back-1    |          ^^^^^^^^^^^^^^^
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-back-1    | FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/shelf-back/certs/edbtlscert.dev.pem'
shelf-showcase-shelf-back-1    |
shelf-showcase-shelf-worker-1  | Traceback (most recent call last):
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/src/shelf-back/manage.py", line 95, in <module>
shelf-showcase-shelf-worker-1  |     cli()
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/src/shelf-back/manage.py", line 91, in migrate
shelf-showcase-shelf-worker-1  |     asyncio.run(run_migration(schema_declaration))
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
shelf-showcase-shelf-worker-1  |     return runner.run(main)
shelf-showcase-shelf-worker-1  |            ^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
shelf-showcase-shelf-worker-1  |     return self._loop.run_until_complete(task)
shelf-showcase-shelf-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/src/shelf-back/manage.py", line 85, in run_migration
shelf-showcase-shelf-worker-1  |     async with db.create_client() as conn:
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
shelf-showcase-shelf-worker-1  |     return await anext(self.gen)
shelf-showcase-shelf-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/src/shelf-back/app/db.py", line 68, in create_client
shelf-showcase-shelf-worker-1  |     async with edgedb.create_async_client(
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/asyncio_client.py", line 356, in __aenter__
shelf-showcase-shelf-worker-1  |     return await self.ensure_connected()
shelf-showcase-shelf-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/asyncio_client.py", line 336, in ensure_connected
shelf-showcase-shelf-worker-1  |     await self._impl.ensure_connected()
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/base_client.py", line 654, in ensure_connected
shelf-showcase-shelf-worker-1  |     await ch.connect()
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/base_client.py", line 361, in connect
shelf-showcase-shelf-worker-1  |     self._con = await self._pool._get_new_connection()
shelf-showcase-shelf-worker-1  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/base_client.py", line 594, in _get_new_connection
shelf-showcase-shelf-worker-1  |     con = await self._maybe_get_first_connection()
shelf-showcase-shelf-worker-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/asyncio_client.py", line 183, in _maybe_get_first_connection
shelf-showcase-shelf-worker-1  |     return await self._get_first_connection()
shelf-showcase-shelf-worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/base_client.py", line 569, in _get_first_connection
shelf-showcase-shelf-worker-1  |     connect_config, client_config = con_utils.parse_connect_arguments(
shelf-showcase-shelf-worker-1  |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 964, in parse_connect_arguments
shelf-showcase-shelf-worker-1  |     connect_config = _parse_connect_dsn_and_args(
shelf-showcase-shelf-worker-1  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 509, in _parse_connect_dsn_and_args
shelf-showcase-shelf-worker-1  |     has_compound_options = _resolve_config_options(
shelf-showcase-shelf-worker-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 826, in _resolve_config_options
shelf-showcase-shelf-worker-1  |     resolved_config.set_tls_ca_file(*tls_ca_file)
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 222, in set_tls_ca_file
shelf-showcase-shelf-worker-1  |     self._set_param('tls_ca_data', ca_file, source, read_ca_file)
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 196, in _set_param
shelf-showcase-shelf-worker-1  |     validator(value) if validator else value
shelf-showcase-shelf-worker-1  |     ^^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  |   File "/usr/local/lib/python3.11/site-packages/edgedb/con_utils.py", line 219, in read_ca_file
shelf-showcase-shelf-worker-1  |     with open(file_path) as f:
shelf-showcase-shelf-worker-1  |          ^^^^^^^^^^^^^^^
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-worker-1  | FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/shelf-back/certs/edbtlscert.dev.pem'
shelf-showcase-shelf-worker-1  |
shelf-showcase-shelf-back-1 exited with code 1
shelf-showcase-shelf-worker-1 exited with code 1
```

I got it to work once, then I changed some values in the .env file (username and password and "API_BASE_URL"). This caused the entire installation to break.

**Comment by unmade** [comment]
Both containers fails with:
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/shelf-back/certs/edbtlscert.dev.pem'
```

Can you please check that you're correctly mounting cert directory to the shelf-back and shelf-worker containers:

```yaml
   ...
    volumes:
      - ./certs:/usr/src/shelf-back/certs
    ...
```

**Comment by TheDanniCraft** [comment]
They are coorectly mounted, I have also tried to copy the .env file completely new from github and only adjust the ports, unfortunately did not help

**Comment by sommerper** [comment]
Hi!

I have the same problem. I had to change the port 8000 (to 8050) in the two places it was written because I already have something running on that port. Didn't change anything else.
